config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users
  resources :sandwiches, only: [:index, :show], controller: "sandwich_views"  
  scope "/api" do 
    resources :sandwiches
    resources :ingredients
    post "/sandwiches/:id/ingredients/add" => "sandwiches#add_ingredient"
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :sandwich_ingredients
	has_many :sandwiches, through: :sandwich_ingredients
end

app/models/sandwich.rb
class Sandwich < ActiveRecord::Base
	has_many :sandwich_ingredients
	has_many :ingredients, through: :sandwich_ingredients, 
					 after_add: :add_calories
	private

	  def add_calories(ingredient)
	  	self.total_calories += ingredient.calories
	  	self.save
	  end
end

app/models/sandwich_ingredient.rb
class SandwichIngredient < ActiveRecord::Base
  belongs_to :sandwich
  belongs_to :ingredient
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def index
	  ingredients = Ingredient.all
	  render json: ingredients
	end

	def create
	  ingredient = Ingredient.create(ingredient_params)
	  render json: ingredient
	end

	def show
	  ingredient = Ingredient.find_by(id: params[:id])
	  unless ingredient
	    render json: {error: "ingredient not found"},
	    status: 404
	    return
	  end
	  render json: ingredient
	end

	def update
	  ingredient = Ingredient.find_by(id: params[:id])
	  unless ingredient
	    render json: {error: "ingredient not found"},
	    status: 404
	    return
	  end
	  ingredient.update(ingredient_params)
	  render json: ingredient
	end

	def destroy
	  ingredient = Ingredient.find_by(id: params[:id])
	  unless ingredient
	    render json: {error: "ingredient not found"},
	    status: 404
	    return
	  end
	  ingredient.destroy
	  render json: ingredient
	end


	private

	def sandwich_params
	  params.require(:ingredient)
	    .permit(:name, :calories)
	end
end

app/controllers/sandwich_views_controller.rb
class SandwichViewsController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@sandwiches = Sandwich.all
	end

	def show
		@ingredients = Ingredient.all
		@sandwich = Sandwich.includes(:ingredients).find_by(id: params[:id])
	end
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
	def index
	  sandwiches = Sandwich.all
	  render json: sandwiches
	end

	def add_ingredient
		sandwich = Sandwich.find_by(id: params[:id])
		ingredient = Ingredient.find_by(id: params[:ingredient_id])
		sandwich.ingredients.push(ingredient)
		render json: sandwich.to_json(:include => :ingredients)
	end

	def create
	  sandwich = Sandwich.create(sandwich_params)
	  render json: sandwich
	end

	def show
	  sandwich = Sandwich.find_by(id: params[:id])
	  unless sandwich
	    render json: {error: "sandwich not found"},
	    status: 404
	    return
	  end
	  render json: sandwich.to_json(:include => :ingredients)
	end

	def update
	  sandwich = Sandwich.find_by(id: params[:id])
	  unless sandwich
	    render json: {error: "sandwich not found"},
	    status: 404
	    return
	  end
	  sandwich.update(sandwich_params)
	  render json: sandwich
	end

	def destroy
	  sandwich = Sandwich.find_by(id: params[:id])
	  unless sandwich
	    render json: {error: "sandwich not found"},
	    status: 404
	    return
	  end
	  sandwich.destroy
	  render json: sandwich
	end


	private

	def sandwich_params
	  params.require(:sandwich)
	    .permit(:name, :bread_type)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/sandwich_views_helper.rb
module SandwichViewsHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandwichr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sandwich_views/index.html.erb
<% @sandwiches.each do |sandwich| %>
	<%= link_to(sandwich.name, sandwich_path(sandwich))  %>
	<br>
<% end %>

app/views/sandwich_views/show.html.erb
<h2>
	<span class="my-sandwich" data-sandwich-id="<%= @sandwich.id  %>">
		<%= @sandwich.name  %>
	</span>
	<small class="my-sandwich-calories"><%= @sandwich.total_calories  %></small>
</h2>

<ul class="ingredient-list">
	<% @sandwich.ingredients.all.each do |ingredient| %>
		<li>
			<%= ingredient.name  %>
			<%= ingredient.calories  %>
		</li>
	<% end %>
</ul>

<div class="ingredient-box">
		<% @ingredients.each do | ingredient | %>
			<button data-id="<%= ingredient.id %>" class="ingredient-button"><%= ingredient.name  %>
			</button>
		<% end %>
</div>

app/views/static_pages/home.html.erb
<h1> Welcome to Sandwichr </h1>
<h4> Make your own sandwich, or browse from our lovely list </h4>

<% unless user_signed_in? %>
	<%= link_to 'Login', new_user_session_path %>
	<%= link_to 'Register', new_user_registration_path %>
<% else %>
	<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
	<%= link_to 'Sandwiches', sandwiches_path  %>
<% end %>